### ISSUE TITLE
您好， 请问我如何将.sav一步步转为.json呢？

### ISSUE THREAD

**Issue by a361570441** [burpheart/Palworld_Reverse_Note#3]
您好，拜读了您的记录，但是我还是有一些疑惑，因为我不是很了解反编译之类的内容，我该如何将.sav一步步转为.json呢？

**Comment by a361570441** [comment]
另外我尝试使用zlib解压时会有报错，请问您知道是为什么吗

**Comment by burpheart** [comment]
https://github.com/cheahjs/palworld-save-tools
